service: cvs-svc-preparers
configValidationMode: warn
plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: dev
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'xray:PutTraceSegments'
            - 'xray:PutTelemetryRecords'
          Resource:
            - '*'

functions:
  getPreparers:
    environment:
      BRANCH: local
    handler: src/handler.handler
    events:
      - http:
          path: 'preparers'
          method: 'get'

custom:
  serverless-offline:
    httpPort: 3003
  serverless-dynamodb:
    start:
      port: 8006
      inMemory: true
      migrate: true
      seed: true
      noStart: false
      host: 127.0.0.1
    seed:
      preparers:
        sources:
          - table: cvs-local-preparers
            sources: [./tests/resources/preparers.json]
    stages:
      - dev
      - test

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-preparers
        AttributeDefinitions:
          - AttributeName: preparerId
            AttributeType: S
        KeySchema:
          - AttributeName: preparerId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
